### PR TITLE
Added diode bridges

### PR DESCRIPTION
**Pull request by kajusK**
Hello,
I've created some diode bridges footprints.

The pin number one does not match the edge on package as the schematic symbol uses different numbering.

### CODE REVIEW

**Comment by kajusK** [comment]
Any update? It's been opened for over a month....

**Comment by SchrodingersGat** [comment]
@kajusK  do you have a link to the documentation you used to create these so we can check over them?

**Comment by kajusK** [comment]
@SchrodingersGat The datasheets are here
http://www.gme.cz/img/cache/doc/227/056/diodovy-mustek-b250c6000dr-datasheet-1.pdf
http://www.farnell.com/datasheets/25534.pdf
http://www.gme.cz/img/cache/doc/227/046/diodovy-mustek-b250c4000-datasheet-1.pdf

**Comment by SchrodingersGat** [comment]
> Diode_Bridge_15.7x15.7

It looks like you have placed the hole centres based on the maximum tolerance, not the midpoint between the min/max tolerances. e.g. pin3 should be at (10.8, 10.8) not (11.3, 11.3)

> Diode_Bridge_18.5x5.5

Pins should be 5.1mm apart, not 4.6mm (middle-point between upper and lower tolerances)

**Comment by kajusK** [comment]
Oops, thanks, It should be fixed now

**Comment by SchrodingersGat** [comment]
One final thing - can you add designators on the F.Fab layer for each of the pins?

diode

**Comment by kajusK** [comment]
Good point, added

**Comment by SchrodingersGat** [comment]
I noticed that you've marked Pin1 as positive on the straight version whereas Pin3 is positive on the square versions:

diode
pdf

Please swap pins 1 and 3 on the straight version to maintain consistency :)

**Comment by kajusK** [comment]
Oops, my bad. Thanks, fixed

**Comment by SchrodingersGat** [comment]
Almost there!

Can you change the shape of  pin-1 on each device to square (on the straight version you'll need to also make pin 3 round again.

Also on the straight version, shift the entire footprint to the left such that pin-1 is @ (0,0)

Thanks :)

**Comment by kajusK** [comment]
I'm not really sure if the pin 1 shape should be square on all packages, it would make more sense to place the square pin to the cut edge of square packages (the pin 3), also the straight version has a "first" pin marked by cut on the package, so again, It would be better to have it on pin 3.

This way, it's clear how to orient the part during assembly even without the silkscreen printed on PCB. If the pin 1 was square it would be quite misleading for square package and would make no sense for straight one.

The origin set on the middle pin of the package would look strange and doesn't make much sense to me in this case, but sure, I can do it.

The problem is that the diode bridge numbering doesn't match the package orientation and strict following KLC rules in this case is a bit strange and misleading (square pins, origin...)

What's your opinion?

**Comment by SchrodingersGat** [comment]
I tend to agree that the square pin should be used to designate the "primary" pin which in this case is numbered '3'. 

Sometimes strict KLC compliance doesn't make the most logical sense. I think this is one of those cases.

Please make pin-3 the 'primary' pin and we'll see if @diggit  or @pointhi  want to weigh in here.

**Comment by kajusK** [comment]
Aside from setting the pin shape, is there anything else to make it a primary? E.g. should I set the origin to this pin for square packages?

**Comment by kajusK** [comment]
I'm sorry, I kind of forgotten this pull request, is that OK now?

**Comment by SchrodingersGat** [comment]
As no one else has weighed in on this, I'll merge this and if there is any other input on how these should be designated we can deal with that at a later stage. Thanks for your efforts :)

**Pull request merged**
