### PR TITLE
swapping A/K pins of the 2 pins diodes

### PR DESCRIPTION
**Pull request by ricardocrudo**

### CODE REVIEW

**Comment by michal777** [comment]
Looks great.
To reduce problems that users may have:
- the pins should be swapped also in schematic library and all should be merged at the same time,
- users and developers should be informed: https://lists.launchpad.net/kicad-developers/msg17469.html
(do somebody have accounts on all the forums an mailing list and could write the posts?)

**Comment by CarlPoirier** [comment]
We will announce it on the developer mailing list. Do any of you have a
Yahoo account to announce it here
<https://groups.yahoo.com/neo/groups/kicad-users/info>?

**Comment by keruseykaryu** [comment]
I have.

**Comment by ricardocrudo** [comment]
I've done the schematics changes in the pull request #175

**Comment by CarlPoirier** [comment]
Hi Ricardo,

The 3D model of Diode_DO-35_SOD27 will need to be rotated. Also, the 3D model of LED_3mm and LED_5mm is not correct. 

Also I'm not sure where it originates from, but the 3D models of Diode_TO-220_Horizontal* and Diode_TO-247_Vertical are offset.

Besides that, I'm ready to merge!

**Pull request merged**
